imports:
    - { resource: parameters.yml }
    - { resource: @StasmoPanaxBundle/Resources/config/admin.yml }
    - { resource: @StasmoPanaxBundle/Resources/config/security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [StasmoPanaxBundle]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

braincrafted_bootstrap:
    less_filter: lessphp

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_mapping: true

liip_imagine:
    filter_sets:
        thumb_small:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        thumb_medium:
            quality: 75
            filters:
                thumbnail: { size: [300, 200], mode: outbound }

