# cms:
#     resource: @CmfBlogBundle/Resources/config/routing/autoroute_default.yml

_imagine:
    resource: .
    type:     imagine

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

stasmo_panax:
    resource: "@StasmoPanaxBundle/Resources/config/routing.yml"
    prefix:   /

# cmf_create_rest:
#     resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

# cmf_create_image:
#     resource: "@CmfCreateBundle/Resources/config/routing/image.xml"