services:
    sonata.admin.event:
        class: Stasmo\PanaxBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Event" }
        arguments:
            - ~
            - Stasmo\PanaxBundle\Document\Event
            - StasmoPanaxBundle:EventsDocument
        calls:
            - [ setTranslationDomain, [StasmoPanaxBundle]]