security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: %admin_pass%, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login: ~
            logout: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/pics/, roles: ROLE_ADMIN }
        - { path: ^/posts/, roles: ROLE_ADMIN }
        - { path: ^/events/, roles: ROLE_ADMIN }
        - { path: ^/bio/, roles: ROLE_ADMIN }
        - { path: ^/music/, roles: ROLE_ADMIN }
        - { path: ^/videos/, roles: ROLE_ADMIN }