parameters:
#    stasmo_panax.example.class: Stasmo\PanaxBundle\Example

services:
#    stasmo_panax.example:
#        class: %stasmo_panax.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
